package com.sansanich.storygenerator.enums;

public enum ActionTypes {
    ADD_ATTRIBUTE,
    ADD_ITEM,
    ADD_SKILL,
    ADD_MONEY,
    ADD_CHAR_TO_LOCATION,
    ADD_REPUTATION,
    ADD_EFFECT,
    ADD_TRAIT,
    REMOVE_ATTRIBUTE,
    REMOVE_ITEM,
    REMOVE_SKILL,
    REMOVE_MONEY,
    REMOVE_CHAR_TO_LOCATION,
    REMOVE_REPUTATION,
    REMOVE_EFFECT,
    REMOVE_TRAIT,

    KILL_CHAR,
    CREATE_CHAR,

    SKIP_TURNS,

    SET_TRIGGER;

}
